"""SEC EDGAR MCP sunucusu - mcp v2.0.0 (2026-07-28 spesifikasyonu).

DIKKAT: v2'de giris noktasi FastMCP degil MCPServer'dir.
    v1:  from mcp.server.fastmcp import FastMCP
    v2:  from mcp.server import MCPServer
"""
from __future__ import annotations

import re
from datetime import date
from typing import Annotated, Literal

import httpx
from mcp.server import MCPServer
from mcp.types import ToolAnnotations
from pydantic import BaseModel, Field

from .belge import bolum_sec, bolumler, metne_cevir
from .client import SEC_WWW, EdgarClient

mcp = MCPServer(
    name="sec-edgar",
    version="0.1.0",
    instructions=(
        "Reads XBRL financial data and filing history for US public companies "
        "from SEC EDGAR through deterministic tool calls. All values come from "
        "the SEC's official REST API and are never generated by the model."
    ),
)

# ---------------------------------------------------------------- kavramlar
# ISS-1 (bkz. CLAUDE.md KK-4): sirketler ayni finansal kalemi farkli US-GAAP
# etiketleriyle raporlar. Apple geliri "Revenues" ile DEGIL
# "RevenueFromContractWithCustomerExcludingAssessedTax" ile bildirir. Modelin
# dogru etiketi tahmin etmesini beklemek basarisiz arac cagrilari uretir.
# Cozum: anlamli takma adlar + aday etiketlerin sirali denenmesi.
CONCEPT_ALIASES: dict[str, list[str]] = {
    "revenue": [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "Revenues",
        "SalesRevenueNet",
    ],
    "gross_profit": ["GrossProfit"],
    "operating_income": ["OperatingIncomeLoss"],
    "net_income": ["NetIncomeLoss"],
    "eps_diluted": ["EarningsPerShareDiluted"],
    "total_assets": ["Assets"],
    "total_liabilities": ["Liabilities"],
    "stockholders_equity": ["StockholdersEquity"],
    "cash": [
        "CashAndCashEquivalentsAtCarryingValue",
        "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
    ],
    "operating_cash_flow": ["NetCashProvidedByUsedInOperatingActivities"],
    "rnd_expense": ["ResearchAndDevelopmentExpense"],
    "capex": ["PaymentsToAcquirePropertyPlantAndEquipment"],
    # `dei` taksonomisi: sirketin kapak sayfasi verisi. Olculdu (14 Agu 2026,
    # `arac/tani.py TSLA --envanter`): companyfacts'te dei/us-gaap/ffd var,
    # sirkete ozel taksonomi YOK. Piyasa degerine SEC icinde kalarak
    # ulasilabilecek tek capa EntityPublicFloat.
    "public_float": ["dei:EntityPublicFloat"],
    "shares_outstanding": ["dei:EntityCommonStockSharesOutstanding"],
    "shares_diluted": ["WeightedAverageNumberOfDilutedSharesOutstanding"],
}

VARSAYILAN_TAKSONOMI = "us-gaap"

ALIAS_LIST = ", ".join(sorted(CONCEPT_ALIASES))


def _bol(tag: str) -> tuple[str, str]:
    """`dei:EntityPublicFloat` -> ("dei", "EntityPublicFloat").
    Onek yoksa us-gaap varsayilir; mevcut cagrilarin hepsi oyle."""
    if ":" in tag:
        tax, _, ad = tag.partition(":")
        return tax.strip(), ad.strip()
    return VARSAYILAN_TAKSONOMI, tag


def _gun_farki(start: str, end: str) -> int:
    a = date(*(int(x) for x in start.split("-")))
    b = date(*(int(x) for x in end.split("-")))
    return (b - a).days


def _yil(end: str) -> int:
    return int(end.split("-")[0])


def _fy_kaymasi(rows: list[dict]) -> tuple[int, bool]:
    """Sirketin mali yil ADLANDIRMA kaymasini SEC verisinden turetir.

    Neden heuristik degil (bkz. CLAUDE.md KK-7): "Ocak-Haziran'da biten donem
    onceki yila sayilir" kurali olculdu ve WMT/NKE/MSFT'de YANLIS cikti. Ters
    kural da guvenli degil - Target/Gap Subat'ta biten yili BASLADIGI yilla
    adlandirir. Yani evrensel bir kural yok.

    Turetme: SEC'in `fy` alani bir 10-K'nin KENDI donemi icin dogrudur (DEI
    DocumentFiscalYearFocus'tan gelir); yanlis olan sadece ayni dosyalamadaki
    karsilastirma yillaridir. Her `fy` grubunda en gec biten donem, o
    dosyalamanin kendi donemidir -> capa. kayma = fy - bitis_yili.

    Doner: (kayma, veriden_turetildi_mi). Capa yoksa (0, False).
    """
    capalar: dict[int, str] = {}
    for r in rows:
        if r.get("fp") != "FY" or not str(r.get("form", "")).startswith("10-K"):
            continue
        end, start, fy = r.get("end"), r.get("start"), r.get("fy")
        if not end or fy is None:
            continue
        if start and not (300 <= _gun_farki(start, end) <= 400):
            continue
        if fy not in capalar or end > capalar[fy]:
            capalar[fy] = end

    if not capalar:
        return 0, False

    kaymalar = [fy - _yil(end) for fy, end in capalar.items()]
    # En sik gorulen kayma; tek tuk transition period'lar sonucu bozmasin.
    # Esitlikte kucuk kayma kazanir - sonuc deterministik olsun.
    kayma = sorted(set(kaymalar), key=lambda k: (-kaymalar.count(k), k))[0]
    return kayma, True

_client: EdgarClient | None = None


def _c() -> EdgarClient:
    global _client
    if _client is None:
        _client = EdgarClient()
    return _client


# ----------------------------------------------------------------- semalar
class CompanyProfile(BaseModel):
    cik: str = Field(description="10-digit zero-padded SEC Central Index Key")
    name: str = Field(description="Official registrant name as filed with the SEC")
    ticker: str
    sic_description: str | None = Field(default=None, description="Standard Industrial Classification description")
    fiscal_year_end: str | None = Field(default=None, description="Fiscal year end as MMDD, e.g. 0927")


class Filing(BaseModel):
    form: str = Field(description="Filing type, e.g. 10-K, 10-Q, 8-K")
    filing_date: str = Field(description="Date the filing was submitted, ISO 8601")
    report_date: str | None = None
    accession_number: str
    primary_document_url: str


class FilingPage(BaseModel):
    ticker: str
    total_matching: int = Field(
        description="Total filings matching form_type in the recent-filings feed"
    )
    returned: int = Field(description="Number of filings in this response")
    has_more: bool = Field(
        description="True if more filings matched than were returned; raise limit "
        "or narrow with form_type"
    )
    filings: list[Filing]


class FactPoint(BaseModel):
    fiscal_year: int = Field(
        description="The company's own fiscal year label, derived from SEC data rather than guessed"
    )
    source_tag: str = Field(description="US-GAAP tag this value was reported under")
    period_start: str | None = Field(default=None, description="Period start date; empty for instant (point-in-time) facts")
    period_end: str = Field(description="Period end date - the only reliable identifier of a period")
    days: int | None = Field(default=None, description="Period length in days")
    value: float
    unit: str
    form: str = Field(description="Filing type the value was taken from")
    filed: str = Field(description="Date this value was filed with the SEC")


class ConceptSeries(BaseModel):
    cik: str
    requested_concept: str = Field(description="The alias or tag the caller supplied")
    resolved_concepts: list[str] = Field(
        description="US-GAAP tags that returned data and were MERGED into this series"
    )
    fiscal_year_derived: bool = Field(
        description="True: fiscal year labels were derived from the company's own SEC "
        "filings. False: no anchor filing was found, so the calendar year of the "
        "period end was used instead - treat these labels as less reliable."
    )
    taxonomy: str
    label: str | None = None
    source_endpoint: str = Field(
        default="companyconcept",
        description="Which SEC endpoint supplied these facts. Normally "
        "companyconcept. It reads companyfacts instead when companyconcept "
        "answered with no facts at all, which SEC does for some companies in "
        "some regions.",
    )
    total_periods: int = Field(
        description="Periods available after merging and de-duplication"
    )
    returned: int = Field(description="Periods in this response")
    has_more: bool = Field(
        description="True if older periods exist beyond this response; the most "
        "recent are returned first-to-last, so raise limit to reach further back"
    )
    points: list[FactPoint]


class RevisionEntry(BaseModel):
    value: float
    unit: str
    first_reported_in: str = Field(
        description="Form type of the earliest filing that carried this value"
    )
    filed: str = Field(description="Date that filing was submitted")
    accession_number: str | None = Field(
        default=None, description="Accession number of that filing"
    )
    source_tag: str = Field(description="US-GAAP tag the value was reported under")
    times_repeated: int = Field(
        description="How many filings carried this same value, including the first"
    )


class FactRevision(BaseModel):
    source_tag: str = Field(
        description="US-GAAP tag this period was reported under. Revisions are "
        "tracked per tag: two tags reporting the same period with different "
        "values is a tagging difference, not a restatement."
    )
    period_end: str
    period_start: str | None = None
    days: int | None = None
    unit: str
    first_value: float = Field(description="Value as first reported to the SEC")
    latest_value: float = Field(description="Value as most recently reported")
    change: float = Field(description="latest_value - first_value")
    change_percent: float | None = Field(
        default=None, description="Percent change; empty when the first value is zero"
    )
    distinct_values: int = Field(
        description="How many different values this period has been reported with"
    )
    entries: list[RevisionEntry] = Field(
        description="One row per distinct value, oldest filing first"
    )


class RevisionReport(BaseModel):
    cik: str
    requested_concept: str
    resolved_concepts: list[str]
    source_endpoint: str = Field(
        default="companyconcept",
        description="Which SEC endpoint supplied these facts"
    )
    periods_examined: int = Field(
        description="Periods that had at least one reported value"
    )
    periods_revised: int = Field(
        description="Periods whose reported value changed at least once"
    )
    returned: int = Field(description="Periods in this response")
    has_more: bool = Field(
        description="True if more periods matched than were returned; raise limit"
    )
    revisions: list[FactRevision] = Field(
        description="Most recent period last"
    )


class FilingDocument(BaseModel):
    name: str = Field(description="File name; pass it back as document")
    size_bytes: int | None = Field(
        default=None, description="Size on SEC's server. Bigger does not mean "
        "more content: a cover page carrying inline-XBRL markup can outweigh "
        "the press release that holds the numbers"
    )
    is_primary: bool = Field(
        default=False,
        description="True for the document SEC lists as the filing's primary "
        "one. On an 8-K that is normally the cover page, and the substance is "
        "in an exhibit — one of the other files here",
    )


class SearchHit(BaseModel):
    position: int = Field(
        description="Character offset of the match; pass it as offset to read "
        "onward from here"
    )
    context: str = Field(description="Text around the match")


class FilingText(BaseModel):
    accession_number: str
    form: str
    filing_date: str
    document_name: str = Field(description="File that was read")
    document_url: str = Field(description="The document this text was read from")
    available_documents: list[FilingDocument] = Field(
        default_factory=list,
        description="Readable files in this filing, largest first. A form 8-K "
        "usually carries its substance in an exhibit rather than in the "
        "primary document, so check this list before concluding a filing is "
        "empty. Pass a name as document to read it.",
    )
    search_query: str | None = Field(default=None, description="The search that was run")
    search_total_matches: int = Field(
        default=0, description="How many times the search text occurs"
    )
    search_hits: list[SearchHit] = Field(
        default_factory=list,
        description="Where the search text occurs, with surrounding context; "
        "capped, so read search_total_matches to know if more exist",
    )
    available_sections: list[str] = Field(
        description="Section headings found in this filing, in document order. "
        "Pass one of these back as section. Table-of-contents entries are "
        "excluded: a heading only counts when real text follows it."
    )
    section_matched: str | None = Field(
        default=None,
        description="Heading this response was cut from; empty when the whole "
        "document was read",
    )
    total_characters: int = Field(
        description="Characters in the selected section, or in the whole "
        "document when no section was given"
    )
    offset: int = Field(description="Where this chunk starts")
    returned_characters: int = Field(description="Characters in this response")
    has_more: bool = Field(
        description="True if text remains after this chunk; call again with "
        "offset = offset + returned_characters"
    )
    text: str


class ConceptInfo(BaseModel):
    tag: str = Field(description="US-GAAP tag; can be passed verbatim to sec_edgar_get_concept_series")
    label: str | None = Field(default=None, description="Human-readable label as published by the SEC")
    units: list[str] = Field(description="Units available for this tag, e.g. USD, shares")
    data_points: int = Field(description="Number of reported data points for this tag")


class ConceptCatalog(BaseModel):
    cik: str
    taxonomy: str = Field(
        default="us-gaap",
        description="Which taxonomy these tags come from",
    )
    available_taxonomies: list[str] = Field(
        default_factory=list,
        description="Every taxonomy this company reports facts under. us-gaap "
        "holds the financial statements; dei holds cover-page facts such as "
        "public float and shares outstanding. Pass one of these as taxonomy.",
    )
    total_matching: int = Field(description="Total number of tags matching the filter")
    returned: int = Field(description="Number of tags returned in this response")
    has_more: bool = Field(description="True if more tags matched than were returned; narrow with search")
    concepts: list[ConceptInfo]


# ----------------------------------------------------------------- araclar
@mcp.tool(
    name="sec_edgar_get_company_profile",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Resolves a ticker symbol to the company's SEC identity: CIK, official "
        "registrant name, industry classification and fiscal year end. Usually "
        "the first tool to call, since the other tools key off the company."
    )
)
async def get_company_profile(
    ticker: Annotated[str, Field(description="Stock ticker symbol, e.g. AAPL")],
) -> CompanyProfile:
    c = _c()
    cik = await c.cik_for_ticker(ticker)
    sub = await c.submissions(cik)
    return CompanyProfile(
        cik=cik,
        name=sub.get("name", ""),
        ticker=ticker.upper(),
        sic_description=sub.get("sicDescription"),
        fiscal_year_end=sub.get("fiscalYearEnd"),
    )


@mcp.tool(
    name="sec_edgar_list_filings",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Lists a company's most recent SEC filings with links to the primary "
        "document. Pass form_type to restrict to one kind of filing, e.g. '10-K' "
        "for annual reports or '10-Q' for quarterly reports."
    )
)
async def list_recent_filings(
    ticker: Annotated[str, Field(description="Stock ticker symbol")],
    form_type: Annotated[
        str | None,
        Field(default=None,
              description="Restrict to one filing type, e.g. 10-K. Omit to return all types."),
    ] = None,
    limit: Annotated[
        int,
        Field(
            default=10, ge=1, le=50,
            description="Maximum number of filings to return, newest first",
        ),
    ] = 10,
) -> FilingPage:
    c = _c()
    cik = await c.cik_for_ticker(ticker)
    sub = await c.submissions(cik)
    r = sub["filings"]["recent"]

    dosyalamalar: list[Filing] = []
    for i in range(len(r["accessionNumber"])):
        if form_type and r["form"][i] != form_type:
            continue
        acc = r["accessionNumber"][i]
        acc_nodash = acc.replace("-", "")
        dosyalamalar.append(
            Filing(
                form=r["form"][i],
                filing_date=r["filingDate"][i],
                report_date=r["reportDate"][i] or None,
                accession_number=acc,
                primary_document_url=(
                    f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/"
                    f"{acc_nodash}/{r['primaryDocument'][i]}"
                ),
            )
        )

    # §16: limit tek basina yetmez. Model, gordugu listenin tamami mi yoksa
    # kirpilmis mi oldugunu bilmeden "sirketin N dosyalamasi var" diye
    # sonuclandirabilir.
    return FilingPage(
        ticker=ticker.upper(),
        total_matching=len(dosyalamalar),
        returned=min(limit, len(dosyalamalar)),
        has_more=len(dosyalamalar) > limit,
        filings=dosyalamalar[:limit],
    )


async def _ham_kayitlar(cik: str, tag: str) -> dict | None:
    """Tek etiketin ham companyconcept yaniti. Etiket yoksa None."""
    taksonomi, ad = _bol(tag)
    try:
        return await _c().company_concept(cik, ad, taxonomy=taksonomi)
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 404:
            return None
        raise


def _kullanilabilir_birimler(veri: dict) -> list[tuple[str, list]]:
    """Yalnizca islenebilir birimler: (birim, satir_listesi).

    SEC'in bos yanitinda `units.USD` bir dizi DEGIL bos bir SOZLUK olarak
    geliyor (ham govde: {"units":{"USD":{}}}). Bu eleme tek noktada yapilir;
    sayim, mali yil turetme ve nokta uretimi ayni kaynagi kullansin diye -
    ayri ayri kontrol koymak, birini unutunca `'str' object has no attribute
    'get'` seklinde patliyordu (P-19).
    """
    return [
        (birim, satirlar)
        for birim, satirlar in (veri.get("units") or {}).items()
        if isinstance(satirlar, list)
    ]


def _satir_sayisi(veriler: list[tuple[str, dict]]) -> int:
    return sum(len(rows) for _, v in veriler for _, rows in _kullanilabilir_birimler(v))


def _facts_kayit(facts: dict, tag: str) -> dict | None:
    """companyfacts yanitindan tek etiketi companyconcept sekline cevirir.
    Ikisinin satir yapisi ayni (end/start/val/form/filed), sarmalayici farkli."""
    taksonomi, ad = _bol(tag)
    govde = (facts.get("facts") or {}).get(taksonomi) or {}
    kayit = govde.get(ad)
    if not kayit:
        return None
    if not any(rows for _, rows in _kullanilabilir_birimler(kayit)):
        return None
    return {"label": kayit.get("label"), "units": kayit.get("units") or {}}


def _donem_uyuyor(period: str, days: int | None) -> bool:
    """Donem filtresi TEK yerde. Seri ve revizyon araclari ayni kurali
    kullanmali; kopyalanirsa biri duzeltilip oteki unutulur ve ayrica
    enjeksiyon hedefi benzersiz olmaktan cikar (KK-18).

    Yillik = 300-400 gun, ceyreklik = 60-120 gun. Ani (instant) kayitlarda
    `days` yoktur: yillik ve 'all' bunlari kabul eder, ceyreklik etmez.
    """
    if period == "quarterly" and days is None:
        return False
    if period == "all" or days is None:
        return True
    if period == "annual":
        return 300 <= days <= 400
    return 60 <= days <= 120


def _noktalar(veri: dict, tag: str, period: str, kayma: int) -> list[FactPoint]:
    out: list[FactPoint] = []
    for unit, rows in _kullanilabilir_birimler(veri):
        for row in rows:
            end = row.get("end")
            if not end:
                continue
            start = row.get("start")
            days = _gun_farki(start, end) if start else None

            # SEC'in fy/fp alanlari DOSYALAMANIN donemini gosterir, verinin
            # kendi donemini DEGIL (KK-1). Donem start/end'den belirlenir.
            if not _donem_uyuyor(period, days):
                continue

            out.append(
                FactPoint(
                    fiscal_year=_yil(end) + kayma,
                    source_tag=tag,
                    period_start=start,
                    period_end=end,
                    days=days,
                    value=float(row["val"]),
                    unit=unit,
                    form=row.get("form", ""),
                    filed=row.get("filed", ""),
                )
            )
    return out


async def _kavram_verisi(
    ticker: str, concept: str
) -> tuple[str, list[str], list[tuple[str, dict]], str]:
    """Takma ad cozumu + aday etiketlerin cekilmesi + bos yanit yedegi.

    Iki arac da (seri ve revizyon gecmisi) ayni yolu kullanir; ayri ayri
    yazilirsa biri duzeltilip oteki unutulur. Doner:
    (cik, aday_etiketler, [(etiket, ham_yanit)], hangi_uc).
    """
    cik = await _c().cik_for_ticker(ticker)
    anahtar = concept.strip().lower()
    adaylar = CONCEPT_ALIASES.get(anahtar, [concept.strip()])

    # H-2 (KK-8): ilk eslesende DURMA. Sirketler muhasebe standardi degisince
    # etiket degistirir (Apple 2018'de SalesRevenueNet -> ASC 606 etiketi).
    # Ilk eslesende durmak 10 yillik gecmisi sessizce kirpiyordu.
    veriler: list[tuple[str, dict]] = []
    for tag in adaylar:
        v = await _ham_kayitlar(cik, tag)
        if v is not None:
            veriler.append((tag, v))

    # KO olayi (13 Agu 2026): SEC bazi sirketler icin companyconcept ucundan
    # HTTP 200 + dogru label + BOS units donduruyor; ayni veri companyfacts
    # ucunda duruyor. Olculdu: kullanicinin aginda bes farkli kosulda da bos,
    # baska bir agdan ayni adres dolu. Bizim tarafta duzeltilebilecek kisim,
    # bos yaniti basari sayip sessizce donmemek.
    kaynak_uc = "companyconcept"
    if veriler and _satir_sayisi(veriler) == 0:
        facts = await _c().company_facts(cik)
        yedek = [(t, kyt) for t in adaylar if (kyt := _facts_kayit(facts, t))]
        if yedek:
            veriler, kaynak_uc = yedek, "companyfacts"

    son_satir = _satir_sayisi(veriler) if veriler else None
    if son_satir == 0:
        raise ValueError(
            f"SEC returned no facts for {ticker} under "
            f"{', '.join(t for t, _ in veriler)}. Both the companyconcept and "
            "the companyfacts endpoint were read and both came back without "
            "data, so this is not a truncated answer - there is nothing to "
            "return. Call sec_edgar_list_available_concepts to see which tags "
            "this company reports."
        )

    if not veriler:
        denenen = ", ".join(adaylar)
        if anahtar in CONCEPT_ALIASES:
            raise ValueError(
                f"No data found for {ticker} under any tag mapped to the alias "
                f"'{concept}' (tried: {denenen}). Call "
                f"sec_edgar_list_available_concepts with "
                f"search='{anahtar.split('_')[0]}' to see which tags this "
                f"company actually reports."
            )
        raise ValueError(
            f"Tag '{concept}' not found for {ticker}. "
            f"Try one of these aliases first: {ALIAS_LIST}. "
            f"Or call sec_edgar_list_available_concepts with "
            f"search='{concept[:12]}' to list the tags this company reports."
        )

    return cik, adaylar, veriler, kaynak_uc


@mcp.tool(
    name="sec_edgar_get_concept_series",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Returns the reported time series for one financial concept (revenue, "
        "net income, total assets, ...). Use this for trend and ratio analysis.\n"
        "The most reliable way to call it is with one of THESE ALIASES: "
        f"{ALIAS_LIST}.\n"
        "An alias merges every US-GAAP tag the company has used for that concept "
        "over time, so history is not silently truncated when a company switches "
        "tags after an accounting standard change. A raw US-GAAP tag is also "
        "accepted. If nothing is found, the error message explains how to "
        "proceed."
    ),
)
async def get_concept_series(
    ticker: Annotated[str, Field(description="Stock ticker symbol, e.g. AAPL")],
    concept: Annotated[
        str,
        Field(
            description=(
                "An alias (revenue, net_income, total_assets, ...) or a raw "
                "US-GAAP tag (e.g. NetIncomeLoss). Call "
                "sec_edgar_list_available_concepts to discover the tags a "
                "company actually reports."
            )
        ),
    ],
    period: Annotated[
        Literal["annual", "quarterly", "all"],
        Field(default="annual", description="annual = periods spanning roughly one year; quarterly = roughly one quarter"),
    ] = "annual",
    limit: Annotated[
        int,
        Field(
            default=12, ge=1, le=60,
            description="Maximum number of periods to return, most recent last",
        ),
    ] = 12,
) -> ConceptSeries:
    cik, adaylar, veriler, kaynak_uc = await _kavram_verisi(ticker, concept)

    # H-1 (KK-7): mali yil adi tum kayitlardan turetilir, tahmin edilmez.
    tum_satirlar = [
        r for _, v in veriler for _, rows in _kullanilabilir_birimler(v) for r in rows
    ]
    kayma, turetildi = _fy_kaymasi(tum_satirlar)

    noktalar: list[FactPoint] = []
    for tag, v in veriler:
        noktalar.extend(_noktalar(v, _bol(tag)[1], period, kayma))

    # Ayni donem hem birden fazla dosyalamada hem birden fazla etikette gecer.
    # En son SUNULAN kayit kazanir; esitlikte takma ad sirasi belirler.
    oncelik = {t: i for i, t in enumerate(adaylar)}
    dedup: dict[tuple[str, str], FactPoint] = {}
    for pt in noktalar:
        k = (pt.period_end, pt.unit)
        mevcut = dedup.get(k)
        if mevcut is None or (pt.filed, -oncelik.get(pt.source_tag, 99)) > (
            mevcut.filed,
            -oncelik.get(mevcut.source_tag, 99),
        ):
            dedup[k] = pt

    # §16: model, gordugu serinin tamami mi yoksa en yenisi mi oldugunu
    # bilmeden "sirketin N donemlik gecmisi var" diye sonuclandirabilir.
    tumu = sorted(dedup.values(), key=lambda p: p.period_end)
    ordered = tumu[-limit:]

    return ConceptSeries(
        cik=cik,
        requested_concept=concept,
        resolved_concepts=[t for t, _ in veriler],
        fiscal_year_derived=turetildi,
        taxonomy=", ".join(dict.fromkeys(_bol(t)[0] for t, _ in veriler)),
        label=veriler[0][1].get("label"),
        source_endpoint=kaynak_uc,
        total_periods=len(tumu),
        returned=len(ordered),
        has_more=len(tumu) > len(ordered),
        points=ordered,
    )


# Cevrilmis belge metni. Neden ham HTML degil de metin (14 Agu 2026, olculdu):
# 2,2 MB HTML'in metne cevrilmesi 0,61 saniye suruyor ve sayfalama ayni belgeyi
# defalarca ister - her cagride yeniden cevirmek bir bolumu bes parcada okurken
# saniyeleri bosa harciyordu. Metin ayrica HTML'den ~20 kat kucuk.
_BELGE_METNI: dict[str, str] = {}
BELGE_METNI_SINIRI = 3


async def _belge_metni(url: str) -> str:
    if url in _BELGE_METNI:
        return _BELGE_METNI[url]
    metin = metne_cevir(await _c().filing_document(url))
    if len(_BELGE_METNI) >= BELGE_METNI_SINIRI:
        _BELGE_METNI.pop(next(iter(_BELGE_METNI)))
    _BELGE_METNI[url] = metin
    return metin


OKUNABILIR_UZANTILAR = (".htm", ".html", ".txt")
ARAMA_BAGLAM = 220
ARAMA_VURGU_SINIRI = 8

# EDGAR'in XBRL goruntuleyicisinin urettigi rapor dosyalari: R1.htm, R2.htm...
# Olculdu (14 Agu 2026, TSLA 8-K 0001628280-26-046717): R1.htm 38.047 bayt ile
# dosyalamanin EN BUYUK .htm dosyasi - basvuru sahibinin yazdigi hicbir sey
# degil, dei etiketlerinin tablo halinde yeniden cizimi. Elenmezse "en buyuk
# dosya" siralamasinin basina o geciyor.
_URETILEN_RAPOR = re.compile(r"^R\d+\.html?$", re.IGNORECASE)

_DIZIN_LISTESI: dict[str, list[FilingDocument]] = {}


async def _okunabilir_belgeler(dizin_url: str, birincil: str) -> list[FilingDocument]:
    """Dosyalamadaki okunabilir dosyalar, buyukten kucuge.

    Siralama bir IPUCU, kural degil. Ilk tasarimda "en buyuk okunabilir dosya
    aranan metindir" varsayilmisti; gercek dosyalamada olcup yanlisladim
    (14 Agu 2026, TSLA 8-K 0001628280-26-046717): kapak sayfasi 26.572 bayt,
    icerigi tasiyan ek 13.243 bayt. Kapak sayfasi satir ici XBRL isaretlemesi
    tasidigi icin daha buyuk. Modelin gercekten ihtiyac duydugu sinyal boyut
    degil, hangi dosyanin BIRINCIL oldugu: 8-K'da birincil belge kapaktir,
    govde ektedir (bkz. FilingDocument.is_primary).
    """
    if dizin_url in _DIZIN_LISTESI:
        return _DIZIN_LISTESI[dizin_url]
    veri = await _c().filing_index(dizin_url)
    out: list[FilingDocument] = []
    for x in (veri.get("directory") or {}).get("item", []):
        ad = str(x.get("name", ""))
        if not ad.lower().endswith(OKUNABILIR_UZANTILAR):
            continue
        if "index" in ad.lower():          # index-headers.html vb. gezinme sayfalari
            continue
        if _URETILEN_RAPOR.match(ad):      # goruntuleyici ciktisi, dosyalanan belge degil
            continue
        boyut = str(x.get("size") or "").strip()
        out.append(FilingDocument(
            name=ad,
            size_bytes=int(boyut) if boyut.isdigit() else None,
            is_primary=(ad == birincil),
        ))
    out.sort(key=lambda b: (b.size_bytes or 0), reverse=True)
    if len(_DIZIN_LISTESI) >= BELGE_METNI_SINIRI:
        _DIZIN_LISTESI.pop(next(iter(_DIZIN_LISTESI)))
    _DIZIN_LISTESI[dizin_url] = out
    return out


def _ara(metin: str, ifade: str) -> tuple[int, list[SearchHit]]:
    """Ifadenin gectigi yerler ve cevresi. Buyuk/kucuk harf ayrimi yok."""
    hedef = ifade.lower()
    govde = metin.lower()
    vurgular: list[SearchHit] = []
    toplam = 0
    i = govde.find(hedef)
    while i != -1:
        toplam += 1
        if len(vurgular) < ARAMA_VURGU_SINIRI:
            bas = max(0, i - ARAMA_BAGLAM)
            son = min(len(metin), i + len(ifade) + ARAMA_BAGLAM)
            vurgular.append(SearchHit(position=i, context=metin[bas:son].strip()))
        i = govde.find(hedef, i + len(hedef))
    return toplam, vurgular


async def _dosyalama_bul(cik: str, accession: str | None, form_type: str) -> dict:
    """Erisim numarasindan (ya da form turunden) dosyalama kaydini bulur."""
    sub = await _c().submissions(cik)
    r = sub.get("filings", {}).get("recent", {})
    n = len(r.get("accessionNumber", []))
    for i in range(n):
        if accession:
            if r["accessionNumber"][i] != accession:
                continue
        elif r["form"][i] != form_type:
            continue
        return {
            "accession_number": r["accessionNumber"][i],
            "form": r["form"][i],
            "filing_date": r["filingDate"][i],
            "primary_document": r["primaryDocument"][i],
        }
    if accession:
        raise ValueError(
            f"Accession number {accession} is not in the recent filings feed "
            "for this company. Call sec_edgar_list_filings to see the "
            "accession numbers that are available."
        )
    raise ValueError(
        f"No {form_type} filing found for this company in the recent filings "
        "feed. Call sec_edgar_list_filings without form_type to see which "
        "forms it has filed."
    )


@mcp.tool(
    name="sec_edgar_read_filing_text",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Reads the TEXT of a filing - the parts XBRL does not carry: "
        "management's discussion, risk factors, the segment note, the income "
        "tax note, and any other narrative.\n"
        "Call it without a section first: the response lists the headings this "
        "filing actually has, so the next call can name one instead of "
        "guessing. Filings run to millions of characters, so text comes back "
        "in chunks - use offset with the has_more flag to keep reading.\n"
        "Use the XBRL tools for figures and this one for the reasons behind "
        "them."
    ),
)
async def read_filing_text(
    ticker: Annotated[str, Field(description="Stock ticker symbol, e.g. AAPL")],
    accession_number: Annotated[
        str | None,
        Field(
            default=None,
            description="Exact filing to read, as returned by "
            "sec_edgar_list_filings. Omit to read the most recent filing of "
            "form_type.",
        ),
    ] = None,
    form_type: Annotated[
        str,
        Field(default="10-K", description="Form type to read when no accession number is given"),
    ] = "10-K",
    document: Annotated[
        str | None,
        Field(
            default=None,
            description="File to read, as named in available_documents. Omit "
            "to read the filing's primary document. A form 8-K normally keeps "
            "its content in an exhibit, so the primary document alone is a "
            "cover page.",
        ),
    ] = None,
    section: Annotated[
        str | None,
        Field(
            default=None,
            description="Heading to cut out, e.g. 'Item 7' or 'income taxes'. "
            "Omit to read the document from the start. Match is on the "
            "headings listed in available_sections.",
        ),
    ] = None,
    search: Annotated[
        str | None,
        Field(
            default=None,
            description="Text to locate. Use it when the right heading is "
            "unknown: the response reports every position with surrounding "
            "context, and those positions can be passed back as offset.",
        ),
    ] = None,
    offset: Annotated[
        int,
        Field(default=0, ge=0, description="Character position to start from"),
    ] = 0,
    max_characters: Annotated[
        int,
        Field(default=6000, ge=500, le=40000,
              description="Maximum characters of text to return in one call"),
    ] = 6000,
) -> FilingText:
    cik = await _c().cik_for_ticker(ticker)
    kayit = await _dosyalama_bul(cik, accession_number, form_type)

    dizin = (
        f"{SEC_WWW}/Archives/edgar/data/{int(cik)}/"
        f"{kayit['accession_number'].replace('-', '')}"
    )
    belgeler = await _okunabilir_belgeler(dizin, kayit["primary_document"])

    ad = document or kayit["primary_document"]
    if document and not any(b.name == document for b in belgeler):
        raise ValueError(
            f"This filing has no readable file named '{document}'. It has: "
            f"{', '.join(b.name for b in belgeler) or 'none'}."
        )

    url = f"{dizin}/{ad}"
    metin = await _belge_metni(url)

    bulunanlar = bolumler(metin)
    basliklar = [b[0] for b in bulunanlar]

    secilen = None
    if section:
        vurus = bolum_sec(bulunanlar, section)
        if vurus is None:
            raise ValueError(
                f"No section matching '{section}' was found in this filing. "
                f"It has these headings: {'; '.join(basliklar[:25]) or 'none'}. "
                "Call this tool without section to read from the start."
            )
        secilen = vurus[0]
        metin = metin[vurus[1]:vurus[2]]

    vurgular: list[SearchHit] = []
    toplam_vurus = 0
    if search:
        toplam_vurus, vurgular = _ara(metin, search)

    parca = metin[offset:offset + max_characters]
    return FilingText(
        accession_number=kayit["accession_number"],
        form=kayit["form"],
        filing_date=kayit["filing_date"],
        document_name=ad,
        document_url=url,
        available_documents=belgeler,
        search_query=search,
        search_total_matches=toplam_vurus,
        search_hits=vurgular,
        available_sections=basliklar,
        section_matched=secilen,
        total_characters=len(metin),
        offset=offset,
        returned_characters=len(parca),
        has_more=offset + len(parca) < len(metin),
        text=parca,
    )


@mcp.tool(
    name="sec_edgar_get_fact_revisions",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Shows how a reported figure CHANGED across filings. Companies restate: "
        "the same period is reported again in later filings, sometimes with a "
        "different number, and the revised value silently replaces the original "
        "in most data sources.\n"
        "Use this to answer 'was this number restated, when, and by how much', "
        "to check whether a trend rests on revised figures, or before quoting a "
        "historical value in an analysis. Takes the same aliases and raw tags as "
        "sec_edgar_get_concept_series."
    ),
)
async def get_fact_revisions(
    ticker: Annotated[str, Field(description="Stock ticker symbol, e.g. AAPL")],
    concept: Annotated[
        str,
        Field(
            description=(
                "An alias (revenue, net_income, total_assets, ...) or a raw "
                "US-GAAP tag, exactly as in sec_edgar_get_concept_series"
            )
        ),
    ],
    period: Annotated[
        Literal["annual", "quarterly", "all"],
        Field(default="annual", description="annual = periods spanning roughly one year; quarterly = roughly one quarter"),
    ] = "annual",
    only_revised: Annotated[
        bool,
        Field(
            default=True,
            description="True returns only periods whose value changed. Set to "
            "False to also see periods that were never revised.",
        ),
    ] = True,
    limit: Annotated[
        int,
        Field(default=12, ge=1, le=60,
              description="Maximum number of periods to return, most recent last"),
    ] = 12,
) -> RevisionReport:
    cik, adaylar, veriler, kaynak_uc = await _kavram_verisi(ticker, concept)

    # Seri aracindan farki: burada dedup YAPILMAZ. Ayni donemin farkli
    # dosyalamalardaki tum degerleri korunur - revizyonun kendisi cikti.
    gruplar: dict[tuple[str, str, str], list[dict]] = {}
    for tag, v in veriler:
        for birim, satirlar in _kullanilabilir_birimler(v):
            for row in satirlar:
                end = row.get("end")
                if not end:
                    continue
                start = row.get("start")
                days = _gun_farki(start, end) if start else None
                if not _donem_uyuyor(period, days):
                    continue
                gruplar.setdefault((tag, end, birim), []).append(
                    {**row, "_tag": tag, "_start": start, "_days": days}
                )

    revizyonlar: list[FactRevision] = []
    for (tag, end, birim), satirlar in gruplar.items():
        satirlar.sort(key=lambda r: (str(r.get("filed", "")), str(r.get("accn", ""))))

        # Ayni deger bircok dosyalamada tekrarlanir (karsilastirma yillari).
        # Tekrar revizyon degildir; bu yuzden FARKLI degerler sayilir.
        gorulen: dict[float, RevisionEntry] = {}
        sirali_degerler: list[float] = []
        for r in satirlar:
            deger = float(r["val"])
            if deger in gorulen:
                gorulen[deger].times_repeated += 1
                continue
            sirali_degerler.append(deger)
            gorulen[deger] = RevisionEntry(
                value=deger,
                unit=birim,
                first_reported_in=str(r.get("form", "")),
                filed=str(r.get("filed", "")),
                accession_number=r.get("accn"),
                source_tag=r["_tag"],
                times_repeated=1,
            )

        ilk, son = sirali_degerler[0], sirali_degerler[-1]
        revizyonlar.append(
            FactRevision(
                source_tag=tag,
                period_end=end,
                period_start=satirlar[0]["_start"],
                days=satirlar[0]["_days"],
                unit=birim,
                first_value=ilk,
                latest_value=son,
                change=son - ilk,
                change_percent=((son - ilk) / abs(ilk) * 100) if ilk else None,
                distinct_values=len(sirali_degerler),
                entries=[gorulen[d] for d in sirali_degerler],
            )
        )

    incelenen = len(revizyonlar)
    revize = sum(1 for r in revizyonlar if r.distinct_values > 1)
    if only_revised:
        revizyonlar = [r for r in revizyonlar if r.distinct_values > 1]
    revizyonlar.sort(key=lambda r: (r.period_end, r.source_tag))
    kirpik = revizyonlar[-limit:]

    return RevisionReport(
        cik=cik,
        requested_concept=concept,
        resolved_concepts=[t for t, _ in veriler],
        source_endpoint=kaynak_uc,
        periods_examined=incelenen,
        periods_revised=revize,
        returned=len(kirpik),
        has_more=len(revizyonlar) > len(kirpik),
        revisions=kirpik,
    )


@mcp.tool(
    name="sec_edgar_list_available_concepts",
    annotations=ToolAnnotations(
        read_only_hint=True,
        destructive_hint=False,
        idempotent_hint=True,
        open_world_hint=True,
    ),
    description=(
        "Lists the US-GAAP tags a company actually reports to the SEC. Call this "
        "when sec_edgar_get_concept_series cannot find a concept: the returned "
        "'tag' values can be passed straight back into that tool. Narrow the "
        "result with search (case-insensitive substring match on tag and label). "
        "Results are ordered by how many data points each tag has, so the "
        "company's primary line items come first."
    ),
)
async def list_available_concepts(
    ticker: Annotated[str, Field(description="Stock ticker symbol, e.g. AAPL")],
    taxonomy: Annotated[
        str,
        Field(
            default="us-gaap",
            description="Which taxonomy to list. us-gaap is the financial "
            "statements; dei is cover-page data. The response names every "
            "taxonomy this company actually reports under.",
        ),
    ] = "us-gaap",
    search: Annotated[
        str | None,
        Field(default=None, description="Substring to match against tag names and labels, e.g. 'revenue'"),
    ] = None,
    limit: Annotated[
        int,
        Field(
            default=25, ge=1, le=100,
            description="Maximum number of tags to return; check has_more in the response",
        ),
    ] = 25,
) -> ConceptCatalog:
    cik = await _c().cik_for_ticker(ticker)
    facts = await _c().company_facts(cik)
    tumu = facts.get("facts", {}) or {}
    mevcut = list(tumu)
    gaap = tumu.get(taxonomy)
    if gaap is None:
        raise ValueError(
            f"{ticker} reports no facts under the taxonomy '{taxonomy}'. "
            f"This company uses: {', '.join(mevcut)}. Call this tool again "
            "with one of those."
        )

    q = (search or "").strip().lower()
    eslesen: list[ConceptInfo] = []
    for tag, govde in gaap.items():
        etiket = govde.get("label")
        if q and q not in tag.lower() and q not in (etiket or "").lower():
            continue
        birimler = list(govde.get("units", {}).keys())
        sayi = sum(len(v) for v in govde.get("units", {}).values())
        eslesen.append(
            ConceptInfo(tag=tag, label=etiket, units=birimler, data_points=sayi)
        )

    # Cok veri noktasi olan etiketler daha merkezi kalemlerdir; once onlar.
    eslesen.sort(key=lambda c: (-c.data_points, c.tag))
    return ConceptCatalog(
        cik=cik,
        taxonomy=taxonomy,
        available_taxonomies=mevcut,
        total_matching=len(eslesen),
        returned=min(limit, len(eslesen)),
        has_more=len(eslesen) > limit,
        concepts=eslesen[:limit],
    )


def main() -> None:
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
